'\" t
.TH "SYSTEMD\&.INDEX" "7" "" "systemd 246" "systemd.index"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.index \- List all manpages from the systemd project
.SH "3"
.PP
\fB30-systemd-environment-d-generator\fR(8)
\(em Load variables specified by
.br

.SH "B"
.PP
\fBbinfmt.d\fR(5)
\(em Configure additional binary formats for executables at boot
.br
\fBbootctl\fR(1)
\(em Control the firmware and boot manager settings
.br
\fBbootup\fR(7)
\(em System bootup process
.br
\fBbusctl\fR(1)
\(em Introspect the bus
.br

.SH "C"
.PP
\fBcoredump.conf\fR(5)
\(em Core dump storage configuration files
.br
\fBcoredump.conf.d\fR(5)
\(em Core dump storage configuration files
.br
\fBcoredumpctl\fR(1)
\(em Retrieve and process saved core dumps and metadata
.br
\fBcrypttab\fR(5)
\(em Configuration for encrypted block devices
.br

.SH "D"
.PP
\fBdaemon\fR(7)
\(em Writing and packaging system daemons
.br
\fBdnssec-trust-anchors.d\fR(5)
\(em DNSSEC trust anchor configuration files
.br

.SH "E"
.PP
\fBenvironment.d\fR(5)
\(em Definition of user service environment
.br

.SH "F"
.PP
\fBfile-hierarchy\fR(7)
\(em File system hierarchy overview
.br

.SH "H"
.PP
\fBhalt\fR(8)
\(em Halt, power\-off or reboot the machine
.br
\fBhostname\fR(5)
\(em Local hostname configuration file
.br
\fBhostnamectl\fR(1)
\(em Control the system hostname
.br
\fBhwdb\fR(7)
\(em Hardware Database
.br

.SH "I"
.PP
\fBinit\fR(1)
\(em systemd system and service manager
.br

.SH "J"
.PP
\fBjournalctl\fR(1)
\(em Query the systemd journal
.br
\fBjournald.conf\fR(5)
\(em Journal service configuration files
.br
\fBjournald.conf.d\fR(5)
\(em Journal service configuration files
.br
\fBjournald@.conf\fR(5)
\(em Journal service configuration files
.br

.SH "K"
.PP
\fBkernel-command-line\fR(7)
\(em Kernel command line parameters
.br
\fBkernel-install\fR(8)
\(em Add and remove kernel and initramfs images to and from /boot
.br

.SH "L"
.PP
\fBlibnss_myhostname.so.2\fR(8)
\(em Hostname resolution for the locally configured system hostname
.br
\fBlibnss_mymachines.so.2\fR(8)
\(em Hostname resolution for local container instances
.br
\fBlibnss_resolve.so.2\fR(8)
\(em Hostname resolution via
.br
\fBlibnss_systemd.so.2\fR(8)
\(em UNIX user and group name resolution for user/group lookup via Varlink
.br
\fBlibudev\fR(3)
\(em API for enumerating and introspecting local devices
.br
\fBloader.conf\fR(5)
\(em Configuration file for systemd\-boot
.br
\fBlocale.conf\fR(5)
\(em Configuration file for locale settings
.br
\fBlocalectl\fR(1)
\(em Control the system locale and keyboard layout settings
.br
\fBlocaltime\fR(5)
\(em Local timezone configuration file
.br
\fBloginctl\fR(1)
\(em Control the systemd login manager
.br
\fBlogind.conf\fR(5)
\(em Login manager configuration files
.br
\fBlogind.conf.d\fR(5)
\(em Login manager configuration files
.br

.SH "M"
.PP
\fBmachine-id\fR(5)
\(em Local machine ID configuration file
.br
\fBmachine-info\fR(5)
\(em Local machine information file
.br
\fBmachinectl\fR(1)
\(em Control the systemd machine manager
.br
\fBmodules-load.d\fR(5)
\(em Configure kernel modules to load at boot
.br

.SH "N"
.PP
\fBnetworkctl\fR(1)
\(em Query the status of network links
.br
\fBnetworkd.conf\fR(5)
\(em Global Network configuration files
.br
\fBnetworkd.conf.d\fR(5)
\(em Global Network configuration files
.br
\fBnss-myhostname\fR(8)
\(em Hostname resolution for the locally configured system hostname
.br
\fBnss-mymachines\fR(8)
\(em Hostname resolution for local container instances
.br
\fBnss-resolve\fR(8)
\(em Hostname resolution via
.br
\fBnss-systemd\fR(8)
\(em UNIX user and group name resolution for user/group lookup via Varlink
.br

.SH "O"
.PP
\fBorg.freedesktop.hostname1\fR(5)
\(em The D\-Bus interface of systemd\-hostnamed
.br
\fBorg.freedesktop.import1\fR(5)
\(em The D\-Bus interface of systemd\-importd
.br
\fBorg.freedesktop.locale1\fR(5)
\(em The D\-Bus interface of systemd\-localed
.br
\fBorg.freedesktop.LogControl1\fR(5)
\(em D\-Bus interface to query and set logging configuration
.br
\fBorg.freedesktop.login1\fR(5)
\(em The D\-Bus interface of systemd\-logind
.br
\fBorg.freedesktop.machine1\fR(5)
\(em The D\-Bus interface of systemd\-machined
.br
\fBorg.freedesktop.resolve1\fR(5)
\(em The D\-Bus interface of systemd\-resolved
.br
\fBorg.freedesktop.systemd1\fR(5)
\(em The D\-Bus interface of systemd
.br
\fBorg.freedesktop.timedate1\fR(5)
\(em The D\-Bus interface of systemd\-timedated
.br
\fBos-release\fR(5)
\(em Operating system identification
.br

.SH "P"
.PP
\fBpam_systemd\fR(8)
\(em Register user sessions in the systemd login manager
.br
\fBportablectl\fR(1)
\(em Attach, detach or inspect portable service images
.br
\fBpoweroff\fR(8)
\(em Halt, power\-off or reboot the machine
.br
\fBpstore.conf\fR(5)
\(em PStore configuration file
.br
\fBpstore.conf.d\fR(5)
\(em PStore configuration file
.br

.SH "R"
.PP
\fBreboot\fR(8)
\(em Halt, power\-off or reboot the machine
.br
\fBrepart.d\fR(5)
\(em Partition Definition Files for Automatic Boot\-Time Repartitioning
.br
\fBresolvconf\fR(1)
\(em Resolve domain names, IPV4 and IPv6 addresses, DNS resource records, and services; introspect and reconfigure the DNS resolver
.br
\fBresolvectl\fR(1)
\(em Resolve domain names, IPV4 and IPv6 addresses, DNS resource records, and services; introspect and reconfigure the DNS resolver
.br
\fBresolved.conf\fR(5)
\(em Network Name Resolution configuration files
.br
\fBresolved.conf.d\fR(5)
\(em Network Name Resolution configuration files
.br
\fBrunlevel\fR(8)
\(em Print previous and current SysV runlevel
.br

.SH "S"
.PP
\fBsd-boot\fR(7)
\(em A simple UEFI boot manager
.br
\fBsd-bus\fR(3)
\(em A lightweight D\-Bus IPC client library
.br
\fBsd-bus-errors\fR(3)
\(em Standard D\-Bus error names
.br
\fBsd-daemon\fR(3)
\(em APIs for new\-style daemons
.br
\fBsd-event\fR(3)
\(em A generic event loop implementation
.br
\fBsd-hwdb\fR(3)
\(em Read\-only access to the hardware description database
.br
\fBsd-id128\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBsd-journal\fR(3)
\(em APIs for submitting and querying log entries to and from the journal
.br
\fBsd-login\fR(3)
\(em APIs for tracking logins
.br
\fBSD_ALERT\fR(3)
\(em APIs for new\-style daemons
.br
\fBsd_booted\fR(3)
\(em Test whether the system is running the systemd init system
.br
\fBsd_bus_add_fallback\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBsd_bus_add_fallback_vtable\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBsd_bus_add_filter\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBsd_bus_add_match\fR(3)
\(em Add a match rule for incoming message dispatching
.br
\fBsd_bus_add_match_async\fR(3)
\(em Add a match rule for incoming message dispatching
.br
\fBsd_bus_add_node_enumerator\fR(3)
\(em Add a node enumerator for a D\-Bus object path prefix
.br
\fBsd_bus_add_object\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBsd_bus_add_object_manager\fR(3)
\(em Add a D\-Bus object manager for a D\-Bus object sub\-tree
.br
\fBsd_bus_add_object_vtable\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBsd_bus_attach_event\fR(3)
\(em Attach a bus connection object to an event loop
.br
\fBsd_bus_call\fR(3)
\(em Invoke a D\-Bus method call
.br
\fBsd_bus_call_async\fR(3)
\(em Invoke a D\-Bus method call
.br
\fBsd_bus_call_method\fR(3)
\(em Initialize a bus message object and invoke the corresponding D\-Bus method call
.br
\fBsd_bus_call_method_async\fR(3)
\(em Initialize a bus message object and invoke the corresponding D\-Bus method call
.br
\fBsd_bus_call_method_asyncv\fR(3)
\(em Initialize a bus message object and invoke the corresponding D\-Bus method call
.br
\fBsd_bus_call_methodv\fR(3)
\(em Initialize a bus message object and invoke the corresponding D\-Bus method call
.br
\fBsd_bus_can_send\fR(3)
\(em Check which types can be sent over a bus object
.br
\fBsd_bus_close\fR(3)
\(em Close and flush a bus connection
.br
\fBsd_bus_close_unref\fR(3)
\(em Create a new bus object and create or destroy references to it
.br
\fBsd_bus_close_unrefp\fR(3)
\(em Create a new bus object and create or destroy references to it
.br
\fBsd_bus_creds_get_audit_login_uid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_audit_session_id\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_augmented_mask\fR(3)
\(em Retrieve credentials object for the specified PID
.br
\fBsd_bus_creds_get_cgroup\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_cmdline\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_comm\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_description\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_egid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_euid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_exe\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_fsgid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_fsuid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_gid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_mask\fR(3)
\(em Retrieve credentials object for the specified PID
.br
\fBsd_bus_creds_get_owner_uid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_pid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_ppid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_selinux_context\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_session\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_sgid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_slice\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_suid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_supplementary_gids\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_tid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_tid_comm\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_tty\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_uid\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_unique_name\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_unit\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_user_slice\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_user_unit\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_well_known_names\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_has_bounding_cap\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_has_effective_cap\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_has_inheritable_cap\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_has_permitted_cap\fR(3)
\(em Retrieve fields from a credentials object
.br
\fBsd_bus_creds_new_from_pid\fR(3)
\(em Retrieve credentials object for the specified PID
.br
\fBsd_bus_creds_ref\fR(3)
\(em Retrieve credentials object for the specified PID
.br
\fBsd_bus_creds_unref\fR(3)
\(em Retrieve credentials object for the specified PID
.br
\fBsd_bus_creds_unrefp\fR(3)
\(em Retrieve credentials object for the specified PID
.br
\fBsd_bus_default\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBsd_bus_default_flush_close\fR(3)
\(em Close and flush a bus connection
.br
\fBsd_bus_default_system\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBsd_bus_default_user\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBsd_bus_destroy_t\fR(3)
\(em Define the callback function for resource cleanup
.br
\fBsd_bus_detach_event\fR(3)
\(em Attach a bus connection object to an event loop
.br
\fBsd_bus_emit_interfaces_added\fR(3)
\(em Convenience functions for emitting (standard) D\-Bus signals
.br
\fBsd_bus_emit_interfaces_added_strv\fR(3)
\(em Convenience functions for emitting (standard) D\-Bus signals
.br
\fBsd_bus_emit_interfaces_removed\fR(3)
\(em Convenience functions for emitting (standard) D\-Bus signals
.br
\fBsd_bus_emit_interfaces_removed_strv\fR(3)
\(em Convenience functions for emitting (standard) D\-Bus signals
.br
\fBsd_bus_emit_object_added\fR(3)
\(em Convenience functions for emitting (standard) D\-Bus signals
.br
\fBsd_bus_emit_object_removed\fR(3)
\(em Convenience functions for emitting (standard) D\-Bus signals
.br
\fBsd_bus_emit_properties_changed\fR(3)
\(em Convenience functions for emitting (standard) D\-Bus signals
.br
\fBsd_bus_emit_properties_changed_strv\fR(3)
\(em Convenience functions for emitting (standard) D\-Bus signals
.br
\fBsd_bus_emit_signal\fR(3)
\(em Convenience functions for emitting (standard) D\-Bus signals
.br
\fBsd_bus_emit_signalv\fR(3)
\(em Convenience functions for emitting (standard) D\-Bus signals
.br
\fBsd_bus_enqueue_for_read\fR(3)
\(em Re\-enqueue a bus message on a bus connection, for reading
.br
\fBsd_bus_error\fR(3)
\(em sd\-bus error handling
.br
\fBSD_BUS_ERROR_ACCESS_DENIED\fR(3)
\(em Standard D\-Bus error names
.br
\fBsd_bus_error_add_map\fR(3)
\(em Additional sd\-dbus error mappings
.br
\fBSD_BUS_ERROR_ADDRESS_IN_USE\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_AUTH_FAILED\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_BAD_ADDRESS\fR(3)
\(em Standard D\-Bus error names
.br
\fBsd_bus_error_copy\fR(3)
\(em sd\-bus error handling
.br
\fBSD_BUS_ERROR_DISCONNECTED\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_END\fR(3)
\(em Additional sd\-dbus error mappings
.br
\fBSD_BUS_ERROR_FAILED\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_FILE_EXISTS\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_FILE_NOT_FOUND\fR(3)
\(em Standard D\-Bus error names
.br
\fBsd_bus_error_free\fR(3)
\(em sd\-bus error handling
.br
\fBsd_bus_error_get_errno\fR(3)
\(em sd\-bus error handling
.br
\fBsd_bus_error_has_name\fR(3)
\(em sd\-bus error handling
.br
\fBSD_BUS_ERROR_INCONSISTENT_MESSAGE\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_INTERACTIVE_AUTHORIZATION_REQUIRED\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_INVALID_ARGS\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_INVALID_SIGNATURE\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_IO_ERROR\fR(3)
\(em Standard D\-Bus error names
.br
\fBsd_bus_error_is_set\fR(3)
\(em sd\-bus error handling
.br
\fBSD_BUS_ERROR_LIMITS_EXCEEDED\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_MAKE_CONST\fR(3)
\(em sd\-bus error handling
.br
\fBsd_bus_error_map\fR(3)
\(em Additional sd\-dbus error mappings
.br
\fBSD_BUS_ERROR_MAP\fR(3)
\(em Additional sd\-dbus error mappings
.br
\fBSD_BUS_ERROR_MATCH_RULE_INVALID\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_MATCH_RULE_NOT_FOUND\fR(3)
\(em Standard D\-Bus error names
.br
\fBsd_bus_error_move\fR(3)
\(em sd\-bus error handling
.br
\fBSD_BUS_ERROR_NAME_HAS_NO_OWNER\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_NO_MEMORY\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_NO_NETWORK\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_NO_REPLY\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_NO_SERVER\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_NOT_SUPPORTED\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_NULL\fR(3)
\(em sd\-bus error handling
.br
\fBSD_BUS_ERROR_PROPERTY_READ_ONLY\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_SERVICE_UNKNOWN\fR(3)
\(em Standard D\-Bus error names
.br
\fBsd_bus_error_set\fR(3)
\(em sd\-bus error handling
.br
\fBsd_bus_error_set_const\fR(3)
\(em sd\-bus error handling
.br
\fBsd_bus_error_set_errno\fR(3)
\(em sd\-bus error handling
.br
\fBsd_bus_error_set_errnof\fR(3)
\(em sd\-bus error handling
.br
\fBsd_bus_error_set_errnofv\fR(3)
\(em sd\-bus error handling
.br
\fBsd_bus_error_setf\fR(3)
\(em sd\-bus error handling
.br
\fBSD_BUS_ERROR_TIMEOUT\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_UNIX_PROCESS_ID_UNKNOWN\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_UNKNOWN_INTERFACE\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_UNKNOWN_METHOD\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_UNKNOWN_OBJECT\fR(3)
\(em Standard D\-Bus error names
.br
\fBSD_BUS_ERROR_UNKNOWN_PROPERTY\fR(3)
\(em Standard D\-Bus error names
.br
\fBsd_bus_flush\fR(3)
\(em Close and flush a bus connection
.br
\fBsd_bus_flush_close_unref\fR(3)
\(em Create a new bus object and create or destroy references to it
.br
\fBsd_bus_flush_close_unrefp\fR(3)
\(em Create a new bus object and create or destroy references to it
.br
\fBsd_bus_get_address\fR(3)
\(em Set or query the address of the bus connection
.br
\fBsd_bus_get_allow_interactive_authorization\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_get_bus_id\fR(3)
\(em Configure connection mode for a bus object
.br
\fBsd_bus_get_close_on_exit\fR(3)
\(em Control whether to close the bus connection during the event loop exit phase
.br
\fBsd_bus_get_connected_signal\fR(3)
\(em Control emission of local connection establishment signal on bus connections
.br
\fBsd_bus_get_creds_mask\fR(3)
\(em Control feature negotiation on bus connections
.br
\fBsd_bus_get_current_handler\fR(3)
\(em Query information of the callback a bus object is currently running
.br
\fBsd_bus_get_current_message\fR(3)
\(em Query information of the callback a bus object is currently running
.br
\fBsd_bus_get_current_slot\fR(3)
\(em Query information of the callback a bus object is currently running
.br
\fBsd_bus_get_current_userdata\fR(3)
\(em Query information of the callback a bus object is currently running
.br
\fBsd_bus_get_description\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_get_event\fR(3)
\(em Attach a bus connection object to an event loop
.br
\fBsd_bus_get_events\fR(3)
\(em Get the file descriptor, I/O events and timeout to wait for from a message bus object
.br
\fBsd_bus_get_exit_on_disconnect\fR(3)
\(em Control the exit behavior when the bus object disconnects
.br
\fBsd_bus_get_fd\fR(3)
\(em Get the file descriptor, I/O events and timeout to wait for from a message bus object
.br
\fBsd_bus_get_method_call_timeout\fR(3)
\(em Set or query the default D\-Bus method call timeout of a bus object
.br
\fBsd_bus_get_n_queued_read\fR(3)
\(em Get the number of pending bus messages in the read and write queues of a bus connection object
.br
\fBsd_bus_get_n_queued_write\fR(3)
\(em Get the number of pending bus messages in the read and write queues of a bus connection object
.br
\fBsd_bus_get_name_creds\fR(3)
\(em Query bus client credentials
.br
\fBsd_bus_get_name_machine_id\fR(3)
\(em Retrieve a bus client\*(Aqs machine identity
.br
\fBsd_bus_get_owner_creds\fR(3)
\(em Query bus client credentials
.br
\fBsd_bus_get_property\fR(3)
\(em Set or query D\-Bus service properties
.br
\fBsd_bus_get_property_string\fR(3)
\(em Set or query D\-Bus service properties
.br
\fBsd_bus_get_property_strv\fR(3)
\(em Set or query D\-Bus service properties
.br
\fBsd_bus_get_property_trivial\fR(3)
\(em Set or query D\-Bus service properties
.br
\fBsd_bus_get_scope\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_get_sender\fR(3)
\(em Configure default sender for outgoing messages
.br
\fBsd_bus_get_tid\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_get_timeout\fR(3)
\(em Get the file descriptor, I/O events and timeout to wait for from a message bus object
.br
\fBsd_bus_get_unique_name\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_get_watch_bind\fR(3)
\(em Control socket binding watching on bus connections
.br
\fBsd_bus_interface_name_is_valid\fR(3)
\(em Check if a string is a valid bus name or object path
.br
\fBsd_bus_is_anonymous\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_is_bus_client\fR(3)
\(em Configure connection mode for a bus object
.br
\fBsd_bus_is_monitor\fR(3)
\(em Configure connection mode for a bus object
.br
\fBsd_bus_is_open\fR(3)
\(em Check whether the bus connection is open or ready
.br
\fBsd_bus_is_ready\fR(3)
\(em Check whether the bus connection is open or ready
.br
\fBsd_bus_is_server\fR(3)
\(em Configure connection mode for a bus object
.br
\fBsd_bus_is_trusted\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_list_names\fR(3)
\(em Retrieve information about registered names on a bus
.br
\fBsd_bus_match_signal\fR(3)
\(em Add a match rule for incoming message dispatching
.br
\fBsd_bus_match_signal_async\fR(3)
\(em Add a match rule for incoming message dispatching
.br
\fBsd_bus_member_name_is_valid\fR(3)
\(em Check if a string is a valid bus name or object path
.br
\fBsd_bus_message_append\fR(3)
\(em Attach fields to a D\-Bus message based on a type string
.br
\fBsd_bus_message_append_array\fR(3)
\(em Append an array of fields to a D\-Bus message
.br
\fBsd_bus_message_append_array_iovec\fR(3)
\(em Append an array of fields to a D\-Bus message
.br
\fBsd_bus_message_append_array_memfd\fR(3)
\(em Append an array of fields to a D\-Bus message
.br
\fBsd_bus_message_append_array_space\fR(3)
\(em Append an array of fields to a D\-Bus message
.br
\fBsd_bus_message_append_basic\fR(3)
\(em Attach a single field to a message
.br
\fBsd_bus_message_append_string_iovec\fR(3)
\(em Attach a string to a message
.br
\fBsd_bus_message_append_string_memfd\fR(3)
\(em Attach a string to a message
.br
\fBsd_bus_message_append_string_space\fR(3)
\(em Attach a string to a message
.br
\fBsd_bus_message_append_strv\fR(3)
\(em Attach an array of strings to a message
.br
\fBsd_bus_message_appendv\fR(3)
\(em Attach fields to a D\-Bus message based on a type string
.br
\fBsd_bus_message_at_end\fR(3)
\(em Check if a message has been fully read
.br
\fBsd_bus_message_close_container\fR(3)
\(em Create and move between containers in D\-Bus messages
.br
\fBsd_bus_message_copy\fR(3)
\(em Copy the contents of one message to another
.br
\fBsd_bus_message_dump\fR(3)
\(em Produce a string representation of a message for debugging purposes
.br
\fBsd_bus_message_enter_container\fR(3)
\(em Create and move between containers in D\-Bus messages
.br
\fBsd_bus_message_exit_container\fR(3)
\(em Create and move between containers in D\-Bus messages
.br
\fBsd_bus_message_get_allow_interactive_authorization\fR(3)
\(em Set and query bus message metadata
.br
\fBsd_bus_message_get_auto_start\fR(3)
\(em Set and query bus message metadata
.br
\fBsd_bus_message_get_bus\fR(3)
\(em Create a new bus message object and create or destroy references to it
.br
\fBsd_bus_message_get_cookie\fR(3)
\(em Returns the transaction cookie of a message
.br
\fBsd_bus_message_get_creds\fR(3)
\(em Query bus message addressing/credentials metadata
.br
\fBsd_bus_message_get_destination\fR(3)
\(em Set and query bus message addressing information
.br
\fBsd_bus_message_get_errno\fR(3)
\(em Query bus message addressing/credentials metadata
.br
\fBsd_bus_message_get_error\fR(3)
\(em Query bus message addressing/credentials metadata
.br
\fBsd_bus_message_get_expect_reply\fR(3)
\(em Set and query bus message metadata
.br
\fBsd_bus_message_get_interface\fR(3)
\(em Set and query bus message addressing information
.br
\fBsd_bus_message_get_member\fR(3)
\(em Set and query bus message addressing information
.br
\fBsd_bus_message_get_monotonic_usec\fR(3)
\(em Retrieve the sender timestamps and sequence number of a message
.br
\fBsd_bus_message_get_path\fR(3)
\(em Set and query bus message addressing information
.br
\fBsd_bus_message_get_realtime_usec\fR(3)
\(em Retrieve the sender timestamps and sequence number of a message
.br
\fBsd_bus_message_get_reply_cookie\fR(3)
\(em Returns the transaction cookie of a message
.br
\fBsd_bus_message_get_sender\fR(3)
\(em Set and query bus message addressing information
.br
\fBsd_bus_message_get_seqnum\fR(3)
\(em Retrieve the sender timestamps and sequence number of a message
.br
\fBsd_bus_message_get_signature\fR(3)
\(em Query bus message signature
.br
\fBsd_bus_message_get_type\fR(3)
\(em Query bus message addressing/credentials metadata
.br
\fBsd_bus_message_has_signature\fR(3)
\(em Query bus message signature
.br
\fBsd_bus_message_is_empty\fR(3)
\(em Query bus message signature
.br
\fBsd_bus_message_is_method_call\fR(3)
\(em Query bus message addressing/credentials metadata
.br
\fBsd_bus_message_is_method_error\fR(3)
\(em Query bus message addressing/credentials metadata
.br
\fBsd_bus_message_is_signal\fR(3)
\(em Query bus message addressing/credentials metadata
.br
\fBSD_BUS_MESSAGE_METHOD_CALL\fR(3)
\(em Create a new bus message object and create or destroy references to it
.br
\fBSD_BUS_MESSAGE_METHOD_ERROR\fR(3)
\(em Create a new bus message object and create or destroy references to it
.br
\fBSD_BUS_MESSAGE_METHOD_RETURN\fR(3)
\(em Create a new bus message object and create or destroy references to it
.br
\fBsd_bus_message_new\fR(3)
\(em Create a new bus message object and create or destroy references to it
.br
\fBsd_bus_message_new_method_call\fR(3)
\(em Create a method call message
.br
\fBsd_bus_message_new_method_errno\fR(3)
\(em Create an error reply for a method call
.br
\fBsd_bus_message_new_method_errnof\fR(3)
\(em Create an error reply for a method call
.br
\fBsd_bus_message_new_method_error\fR(3)
\(em Create an error reply for a method call
.br
\fBsd_bus_message_new_method_errorf\fR(3)
\(em Create an error reply for a method call
.br
\fBsd_bus_message_new_method_return\fR(3)
\(em Create a method call message
.br
\fBsd_bus_message_new_signal\fR(3)
\(em Create a signal message
.br
\fBsd_bus_message_open_container\fR(3)
\(em Create and move between containers in D\-Bus messages
.br
\fBsd_bus_message_peek_type\fR(3)
\(em Read a sequence of values from a message
.br
\fBsd_bus_message_read\fR(3)
\(em Read a sequence of values from a message
.br
\fBsd_bus_message_read_array\fR(3)
\(em Access an array of elements in a message
.br
\fBsd_bus_message_read_basic\fR(3)
\(em Read a basic type from a message
.br
\fBsd_bus_message_read_strv\fR(3)
\(em Access an array of strings in a message
.br
\fBsd_bus_message_readv\fR(3)
\(em Read a sequence of values from a message
.br
\fBsd_bus_message_ref\fR(3)
\(em Create a new bus message object and create or destroy references to it
.br
\fBsd_bus_message_rewind\fR(3)
\(em Return to beginning of message or current container
.br
\fBsd_bus_message_seal\fR(3)
\(em Prepare a D\-Bus message for transmission
.br
\fBsd_bus_message_sensitive\fR(3)
\(em Mark a message object as containing sensitive data
.br
\fBsd_bus_message_set_allow_interactive_authorization\fR(3)
\(em Set and query bus message metadata
.br
\fBsd_bus_message_set_auto_start\fR(3)
\(em Set and query bus message metadata
.br
\fBsd_bus_message_set_destination\fR(3)
\(em Set and query bus message addressing information
.br
\fBsd_bus_message_set_expect_reply\fR(3)
\(em Set and query bus message metadata
.br
\fBsd_bus_message_set_sender\fR(3)
\(em Set and query bus message addressing information
.br
\fBSD_BUS_MESSAGE_SIGNAL\fR(3)
\(em Create a new bus message object and create or destroy references to it
.br
\fBsd_bus_message_skip\fR(3)
\(em Skip elements in a bus message
.br
\fBsd_bus_message_unref\fR(3)
\(em Create a new bus message object and create or destroy references to it
.br
\fBsd_bus_message_unrefp\fR(3)
\(em Create a new bus message object and create or destroy references to it
.br
\fBsd_bus_message_verify_type\fR(3)
\(em Check if the message has specified type at the current location
.br
\fBSD_BUS_METHOD\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBSD_BUS_METHOD_WITH_NAMES\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBSD_BUS_METHOD_WITH_NAMES_OFFSET\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBSD_BUS_METHOD_WITH_OFFSET\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBsd_bus_negotiate_creds\fR(3)
\(em Control feature negotiation on bus connections
.br
\fBsd_bus_negotiate_fds\fR(3)
\(em Control feature negotiation on bus connections
.br
\fBsd_bus_negotiate_timestamp\fR(3)
\(em Control feature negotiation on bus connections
.br
\fBsd_bus_new\fR(3)
\(em Create a new bus object and create or destroy references to it
.br
\fBsd_bus_object_path_is_valid\fR(3)
\(em Check if a string is a valid bus name or object path
.br
\fBsd_bus_open\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBsd_bus_open_system\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBsd_bus_open_system_machine\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBsd_bus_open_system_remote\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBsd_bus_open_system_with_description\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBsd_bus_open_user\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBsd_bus_open_user_with_description\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBsd_bus_open_with_description\fR(3)
\(em Acquire a connection to a system or user bus
.br
\fBSD_BUS_PARAM\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBsd_bus_path_decode\fR(3)
\(em Convert an external identifier into an object path and back
.br
\fBsd_bus_path_decode_many\fR(3)
\(em Convert an external identifier into an object path and back
.br
\fBsd_bus_path_encode\fR(3)
\(em Convert an external identifier into an object path and back
.br
\fBsd_bus_path_encode_many\fR(3)
\(em Convert an external identifier into an object path and back
.br
\fBsd_bus_process\fR(3)
\(em Drive the connection
.br
\fBSD_BUS_PROPERTY\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBsd_bus_query_sender_creds\fR(3)
\(em Query bus message sender credentials/privileges
.br
\fBsd_bus_query_sender_privilege\fR(3)
\(em Query bus message sender credentials/privileges
.br
\fBsd_bus_ref\fR(3)
\(em Create a new bus object and create or destroy references to it
.br
\fBsd_bus_release_name\fR(3)
\(em Request or release a well\-known service name on a bus
.br
\fBsd_bus_release_name_async\fR(3)
\(em Request or release a well\-known service name on a bus
.br
\fBsd_bus_reply_method_errno\fR(3)
\(em Reply with an error to a D\-Bus method call
.br
\fBsd_bus_reply_method_errnof\fR(3)
\(em Reply with an error to a D\-Bus method call
.br
\fBsd_bus_reply_method_errnofv\fR(3)
\(em Reply with an error to a D\-Bus method call
.br
\fBsd_bus_reply_method_error\fR(3)
\(em Reply with an error to a D\-Bus method call
.br
\fBsd_bus_reply_method_errorf\fR(3)
\(em Reply with an error to a D\-Bus method call
.br
\fBsd_bus_reply_method_errorfv\fR(3)
\(em Reply with an error to a D\-Bus method call
.br
\fBsd_bus_reply_method_return\fR(3)
\(em Reply to a D\-Bus method call
.br
\fBsd_bus_reply_method_returnv\fR(3)
\(em Reply to a D\-Bus method call
.br
\fBsd_bus_request_name\fR(3)
\(em Request or release a well\-known service name on a bus
.br
\fBsd_bus_request_name_async\fR(3)
\(em Request or release a well\-known service name on a bus
.br
\fBsd_bus_send\fR(3)
\(em Queue a D\-Bus message for transfer
.br
\fBsd_bus_send_to\fR(3)
\(em Queue a D\-Bus message for transfer
.br
\fBsd_bus_service_name_is_valid\fR(3)
\(em Check if a string is a valid bus name or object path
.br
\fBsd_bus_set_address\fR(3)
\(em Set or query the address of the bus connection
.br
\fBsd_bus_set_allow_interactive_authorization\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_set_anonymous\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_set_bus_client\fR(3)
\(em Configure connection mode for a bus object
.br
\fBsd_bus_set_close_on_exit\fR(3)
\(em Control whether to close the bus connection during the event loop exit phase
.br
\fBsd_bus_set_connected_signal\fR(3)
\(em Control emission of local connection establishment signal on bus connections
.br
\fBsd_bus_set_description\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_set_exec\fR(3)
\(em Set or query the address of the bus connection
.br
\fBsd_bus_set_exit_on_disconnect\fR(3)
\(em Control the exit behavior when the bus object disconnects
.br
\fBsd_bus_set_fd\fR(3)
\(em Get the file descriptor, I/O events and timeout to wait for from a message bus object
.br
\fBsd_bus_set_method_call_timeout\fR(3)
\(em Set or query the default D\-Bus method call timeout of a bus object
.br
\fBsd_bus_set_monitor\fR(3)
\(em Configure connection mode for a bus object
.br
\fBsd_bus_set_property\fR(3)
\(em Set or query D\-Bus service properties
.br
\fBsd_bus_set_propertyv\fR(3)
\(em Set or query D\-Bus service properties
.br
\fBsd_bus_set_sender\fR(3)
\(em Configure default sender for outgoing messages
.br
\fBsd_bus_set_server\fR(3)
\(em Configure connection mode for a bus object
.br
\fBsd_bus_set_trusted\fR(3)
\(em Set or query properties of a bus object
.br
\fBsd_bus_set_watch_bind\fR(3)
\(em Control socket binding watching on bus connections
.br
\fBSD_BUS_SIGNAL\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBSD_BUS_SIGNAL_WITH_NAMES\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBsd_bus_slot_get_bus\fR(3)
\(em Query information attached to a bus slot object
.br
\fBsd_bus_slot_get_current_handler\fR(3)
\(em Query information attached to a bus slot object
.br
\fBsd_bus_slot_get_current_message\fR(3)
\(em Query information attached to a bus slot object
.br
\fBsd_bus_slot_get_current_userdata\fR(3)
\(em Query information attached to a bus slot object
.br
\fBsd_bus_slot_get_description\fR(3)
\(em Set or query the description of bus slot objects
.br
\fBsd_bus_slot_get_destroy_callback\fR(3)
\(em Define the callback function for resource cleanup
.br
\fBsd_bus_slot_get_floating\fR(3)
\(em Control whether a bus slot object is "floating"
.br
\fBsd_bus_slot_get_userdata\fR(3)
\(em Set and query the value in the "userdata" field
.br
\fBsd_bus_slot_ref\fR(3)
\(em Create and destroy references to a bus slot object
.br
\fBsd_bus_slot_set_description\fR(3)
\(em Set or query the description of bus slot objects
.br
\fBsd_bus_slot_set_destroy_callback\fR(3)
\(em Define the callback function for resource cleanup
.br
\fBsd_bus_slot_set_floating\fR(3)
\(em Control whether a bus slot object is "floating"
.br
\fBsd_bus_slot_set_userdata\fR(3)
\(em Set and query the value in the "userdata" field
.br
\fBsd_bus_slot_unref\fR(3)
\(em Create and destroy references to a bus slot object
.br
\fBsd_bus_slot_unrefp\fR(3)
\(em Create and destroy references to a bus slot object
.br
\fBsd_bus_start\fR(3)
\(em Initiate a bus connection to the D\-bus broker daemon
.br
\fBsd_bus_track_add_name\fR(3)
\(em Add, remove and retrieve bus peers tracked in a bus peer tracking object
.br
\fBsd_bus_track_add_sender\fR(3)
\(em Add, remove and retrieve bus peers tracked in a bus peer tracking object
.br
\fBsd_bus_track_contains\fR(3)
\(em Add, remove and retrieve bus peers tracked in a bus peer tracking object
.br
\fBsd_bus_track_count\fR(3)
\(em Add, remove and retrieve bus peers tracked in a bus peer tracking object
.br
\fBsd_bus_track_count_name\fR(3)
\(em Add, remove and retrieve bus peers tracked in a bus peer tracking object
.br
\fBsd_bus_track_count_sender\fR(3)
\(em Add, remove and retrieve bus peers tracked in a bus peer tracking object
.br
\fBsd_bus_track_first\fR(3)
\(em Add, remove and retrieve bus peers tracked in a bus peer tracking object
.br
\fBsd_bus_track_get_bus\fR(3)
\(em Track bus peers
.br
\fBsd_bus_track_get_destroy_callback\fR(3)
\(em Define the callback function for resource cleanup
.br
\fBsd_bus_track_get_recursive\fR(3)
\(em Track bus peers
.br
\fBsd_bus_track_get_userdata\fR(3)
\(em Track bus peers
.br
\fBsd_bus_track_new\fR(3)
\(em Track bus peers
.br
\fBsd_bus_track_next\fR(3)
\(em Add, remove and retrieve bus peers tracked in a bus peer tracking object
.br
\fBsd_bus_track_ref\fR(3)
\(em Track bus peers
.br
\fBsd_bus_track_remove_name\fR(3)
\(em Add, remove and retrieve bus peers tracked in a bus peer tracking object
.br
\fBsd_bus_track_remove_sender\fR(3)
\(em Add, remove and retrieve bus peers tracked in a bus peer tracking object
.br
\fBsd_bus_track_set_destroy_callback\fR(3)
\(em Define the callback function for resource cleanup
.br
\fBsd_bus_track_set_recursive\fR(3)
\(em Track bus peers
.br
\fBsd_bus_track_set_userdata\fR(3)
\(em Track bus peers
.br
\fBsd_bus_track_unref\fR(3)
\(em Track bus peers
.br
\fBsd_bus_track_unrefp\fR(3)
\(em Track bus peers
.br
\fBsd_bus_unref\fR(3)
\(em Create a new bus object and create or destroy references to it
.br
\fBsd_bus_unrefp\fR(3)
\(em Create a new bus object and create or destroy references to it
.br
\fBSD_BUS_VTABLE_END\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBSD_BUS_VTABLE_START\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBsd_bus_wait\fR(3)
\(em Wait for I/O on a bus connection
.br
\fBSD_BUS_WRITABLE_PROPERTY\fR(3)
\(em Declare properties and methods for a D\-Bus path
.br
\fBSD_CRIT\fR(3)
\(em APIs for new\-style daemons
.br
\fBSD_DEBUG\fR(3)
\(em APIs for new\-style daemons
.br
\fBSD_EMERG\fR(3)
\(em APIs for new\-style daemons
.br
\fBSD_ERR\fR(3)
\(em APIs for new\-style daemons
.br
\fBsd_event\fR(3)
\(em Acquire and release an event loop object
.br
\fBsd_event_add_child\fR(3)
\(em Add a child process state change event source to an event loop
.br
\fBsd_event_add_child_pidfd\fR(3)
\(em Add a child process state change event source to an event loop
.br
\fBsd_event_add_defer\fR(3)
\(em Add static event sources to an event loop
.br
\fBsd_event_add_exit\fR(3)
\(em Add static event sources to an event loop
.br
\fBsd_event_add_inotify\fR(3)
\(em Add an "inotify" file system inode event source to an event loop
.br
\fBsd_event_add_io\fR(3)
\(em Add an I/O event source to an event loop
.br
\fBsd_event_add_post\fR(3)
\(em Add static event sources to an event loop
.br
\fBsd_event_add_signal\fR(3)
\(em Add a UNIX process signal event source to an event loop
.br
\fBsd_event_add_time\fR(3)
\(em Add a timer event source to an event loop
.br
\fBSD_EVENT_ARMED\fR(3)
\(em Low\-level event loop operations
.br
\fBsd_event_child_handler_t\fR(3)
\(em Add a child process state change event source to an event loop
.br
\fBsd_event_default\fR(3)
\(em Acquire and release an event loop object
.br
\fBsd_event_destroy_t\fR(3)
\(em Define the callback function for resource cleanup
.br
\fBsd_event_dispatch\fR(3)
\(em Low\-level event loop operations
.br
\fBsd_event_exit\fR(3)
\(em Ask the event loop to exit
.br
\fBSD_EVENT_EXITING\fR(3)
\(em Low\-level event loop operations
.br
\fBSD_EVENT_FINISHED\fR(3)
\(em Low\-level event loop operations
.br
\fBsd_event_get_exit_code\fR(3)
\(em Ask the event loop to exit
.br
\fBsd_event_get_fd\fR(3)
\(em Obtain a file descriptor to poll for event loop events
.br
\fBsd_event_get_iteration\fR(3)
\(em Low\-level event loop operations
.br
\fBsd_event_get_state\fR(3)
\(em Low\-level event loop operations
.br
\fBsd_event_get_tid\fR(3)
\(em Acquire and release an event loop object
.br
\fBsd_event_get_watchdog\fR(3)
\(em Enable event loop watchdog support
.br
\fBsd_event_handler_t\fR(3)
\(em Add static event sources to an event loop
.br
\fBSD_EVENT_INITIAL\fR(3)
\(em Low\-level event loop operations
.br
\fBsd_event_inotify_handler_t\fR(3)
\(em Add an "inotify" file system inode event source to an event loop
.br
\fBsd_event_io_handler_t\fR(3)
\(em Add an I/O event source to an event loop
.br
\fBsd_event_loop\fR(3)
\(em Run an event loop
.br
\fBsd_event_new\fR(3)
\(em Acquire and release an event loop object
.br
\fBsd_event_now\fR(3)
\(em Retrieve current event loop iteration timestamp
.br
\fBSD_EVENT_OFF\fR(3)
\(em Enable or disable event sources
.br
\fBSD_EVENT_ON\fR(3)
\(em Enable or disable event sources
.br
\fBSD_EVENT_ONESHOT\fR(3)
\(em Enable or disable event sources
.br
\fBSD_EVENT_PENDING\fR(3)
\(em Low\-level event loop operations
.br
\fBsd_event_prepare\fR(3)
\(em Low\-level event loop operations
.br
\fBSD_EVENT_PREPARING\fR(3)
\(em Low\-level event loop operations
.br
\fBSD_EVENT_PRIORITY_IDLE\fR(3)
\(em Set or retrieve the priority of event sources
.br
\fBSD_EVENT_PRIORITY_IMPORTANT\fR(3)
\(em Set or retrieve the priority of event sources
.br
\fBSD_EVENT_PRIORITY_NORMAL\fR(3)
\(em Set or retrieve the priority of event sources
.br
\fBsd_event_ref\fR(3)
\(em Acquire and release an event loop object
.br
\fBsd_event_run\fR(3)
\(em Run an event loop
.br
\fBSD_EVENT_RUNNING\fR(3)
\(em Low\-level event loop operations
.br
\fBsd_event_set_watchdog\fR(3)
\(em Enable event loop watchdog support
.br
\fBsd_event_signal_handler_t\fR(3)
\(em Add a UNIX process signal event source to an event loop
.br
\fBsd_event_source\fR(3)
\(em Add an I/O event source to an event loop
.br
\fBsd_event_source_disable_unref\fR(3)
\(em Increase or decrease event source reference counters
.br
\fBsd_event_source_disable_unrefp\fR(3)
\(em Increase or decrease event source reference counters
.br
\fBsd_event_source_get_child_pid\fR(3)
\(em Add a child process state change event source to an event loop
.br
\fBsd_event_source_get_child_pidfd\fR(3)
\(em Add a child process state change event source to an event loop
.br
\fBsd_event_source_get_child_pidfd_own\fR(3)
\(em Add a child process state change event source to an event loop
.br
\fBsd_event_source_get_child_process_own\fR(3)
\(em Add a child process state change event source to an event loop
.br
\fBsd_event_source_get_description\fR(3)
\(em Set or retrieve descriptive names of event sources
.br
\fBsd_event_source_get_destroy_callback\fR(3)
\(em Define the callback function for resource cleanup
.br
\fBsd_event_source_get_enabled\fR(3)
\(em Enable or disable event sources
.br
\fBsd_event_source_get_event\fR(3)
\(em Retrieve the event loop of an event source
.br
\fBsd_event_source_get_floating\fR(3)
\(em Set or retrieve \*(Aqfloating\*(Aq state of event sources
.br
\fBsd_event_source_get_inotify_mask\fR(3)
\(em Add an "inotify" file system inode event source to an event loop
.br
\fBsd_event_source_get_io_events\fR(3)
\(em Add an I/O event source to an event loop
.br
\fBsd_event_source_get_io_fd\fR(3)
\(em Add an I/O event source to an event loop
.br
\fBsd_event_source_get_io_fd_own\fR(3)
\(em Add an I/O event source to an event loop
.br
\fBsd_event_source_get_io_revents\fR(3)
\(em Add an I/O event source to an event loop
.br
\fBsd_event_source_get_pending\fR(3)
\(em Determine pending state of event sources
.br
\fBsd_event_source_get_priority\fR(3)
\(em Set or retrieve the priority of event sources
.br
\fBsd_event_source_get_signal\fR(3)
\(em Add a UNIX process signal event source to an event loop
.br
\fBsd_event_source_get_time\fR(3)
\(em Add a timer event source to an event loop
.br
\fBsd_event_source_get_time_accuracy\fR(3)
\(em Add a timer event source to an event loop
.br
\fBsd_event_source_get_time_clock\fR(3)
\(em Add a timer event source to an event loop
.br
\fBsd_event_source_get_userdata\fR(3)
\(em Set or retrieve user data pointer of event sources
.br
\fBsd_event_source_ref\fR(3)
\(em Increase or decrease event source reference counters
.br
\fBsd_event_source_send_child_signal\fR(3)
\(em Add a child process state change event source to an event loop
.br
\fBsd_event_source_set_child_pidfd_own\fR(3)
\(em Add a child process state change event source to an event loop
.br
\fBsd_event_source_set_child_process_own\fR(3)
\(em Add a child process state change event source to an event loop
.br
\fBsd_event_source_set_description\fR(3)
\(em Set or retrieve descriptive names of event sources
.br
\fBsd_event_source_set_destroy_callback\fR(3)
\(em Define the callback function for resource cleanup
.br
\fBsd_event_source_set_enabled\fR(3)
\(em Enable or disable event sources
.br
\fBsd_event_source_set_floating\fR(3)
\(em Set or retrieve \*(Aqfloating\*(Aq state of event sources
.br
\fBsd_event_source_set_io_events\fR(3)
\(em Add an I/O event source to an event loop
.br
\fBsd_event_source_set_io_fd\fR(3)
\(em Add an I/O event source to an event loop
.br
\fBsd_event_source_set_io_fd_own\fR(3)
\(em Add an I/O event source to an event loop
.br
\fBsd_event_source_set_prepare\fR(3)
\(em Set a preparation callback for event sources
.br
\fBsd_event_source_set_priority\fR(3)
\(em Set or retrieve the priority of event sources
.br
\fBsd_event_source_set_time\fR(3)
\(em Add a timer event source to an event loop
.br
\fBsd_event_source_set_time_accuracy\fR(3)
\(em Add a timer event source to an event loop
.br
\fBsd_event_source_set_userdata\fR(3)
\(em Set or retrieve user data pointer of event sources
.br
\fBsd_event_source_unref\fR(3)
\(em Increase or decrease event source reference counters
.br
\fBsd_event_source_unrefp\fR(3)
\(em Increase or decrease event source reference counters
.br
\fBsd_event_time_handler_t\fR(3)
\(em Add a timer event source to an event loop
.br
\fBsd_event_unref\fR(3)
\(em Acquire and release an event loop object
.br
\fBsd_event_unrefp\fR(3)
\(em Acquire and release an event loop object
.br
\fBsd_event_wait\fR(3)
\(em Low\-level event loop operations
.br
\fBsd_get_machine_names\fR(3)
\(em Determine available seats, sessions, logged in users and virtual machines/containers
.br
\fBsd_get_seats\fR(3)
\(em Determine available seats, sessions, logged in users and virtual machines/containers
.br
\fBsd_get_sessions\fR(3)
\(em Determine available seats, sessions, logged in users and virtual machines/containers
.br
\fBsd_get_uids\fR(3)
\(em Determine available seats, sessions, logged in users and virtual machines/containers
.br
\fBsd_hwdb_enumerate\fR(3)
\(em Seek to a location in hwdb or access entries
.br
\fBSD_HWDB_FOREACH_PROPERTY\fR(3)
\(em Seek to a location in hwdb or access entries
.br
\fBsd_hwdb_get\fR(3)
\(em Seek to a location in hwdb or access entries
.br
\fBsd_hwdb_new\fR(3)
\(em Create a new hwdb object and create or destroy references to it
.br
\fBsd_hwdb_ref\fR(3)
\(em Create a new hwdb object and create or destroy references to it
.br
\fBsd_hwdb_seek\fR(3)
\(em Seek to a location in hwdb or access entries
.br
\fBsd_hwdb_unref\fR(3)
\(em Create a new hwdb object and create or destroy references to it
.br
\fBSD_ID128_CONST_STR\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBsd_id128_equal\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBSD_ID128_FORMAT_STR\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBSD_ID128_FORMAT_VAL\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBsd_id128_from_string\fR(3)
\(em Format or parse 128\-bit IDs as strings
.br
\fBsd_id128_get_boot\fR(3)
\(em Retrieve 128\-bit IDs
.br
\fBsd_id128_get_boot_app_specific\fR(3)
\(em Retrieve 128\-bit IDs
.br
\fBsd_id128_get_invocation\fR(3)
\(em Retrieve 128\-bit IDs
.br
\fBsd_id128_get_machine\fR(3)
\(em Retrieve 128\-bit IDs
.br
\fBsd_id128_get_machine_app_specific\fR(3)
\(em Retrieve 128\-bit IDs
.br
\fBsd_id128_is_null\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBSD_ID128_MAKE\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBSD_ID128_MAKE_STR\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBSD_ID128_NULL\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBsd_id128_randomize\fR(3)
\(em Generate 128\-bit IDs
.br
\fBsd_id128_t\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBsd_id128_to_string\fR(3)
\(em Format or parse 128\-bit IDs as strings
.br
\fBSD_ID128_UUID_FORMAT_STR\fR(3)
\(em APIs for processing 128\-bit IDs
.br
\fBSD_INFO\fR(3)
\(em APIs for new\-style daemons
.br
\fBsd_is_fifo\fR(3)
\(em Check the type of a file descriptor
.br
\fBsd_is_mq\fR(3)
\(em Check the type of a file descriptor
.br
\fBsd_is_socket\fR(3)
\(em Check the type of a file descriptor
.br
\fBsd_is_socket_inet\fR(3)
\(em Check the type of a file descriptor
.br
\fBsd_is_socket_sockaddr\fR(3)
\(em Check the type of a file descriptor
.br
\fBsd_is_socket_unix\fR(3)
\(em Check the type of a file descriptor
.br
\fBsd_is_special\fR(3)
\(em Check the type of a file descriptor
.br
\fBsd_journal\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_add_conjunction\fR(3)
\(em Add or remove entry matches
.br
\fBsd_journal_add_disjunction\fR(3)
\(em Add or remove entry matches
.br
\fBsd_journal_add_match\fR(3)
\(em Add or remove entry matches
.br
\fBSD_JOURNAL_ALL_NAMESPACES\fR(3)
\(em Open the system journal for reading
.br
\fBSD_JOURNAL_APPEND\fR(3)
\(em Journal change notification interface
.br
\fBsd_journal_close\fR(3)
\(em Open the system journal for reading
.br
\fBSD_JOURNAL_CURRENT_USER\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_enumerate_available_data\fR(3)
\(em Read data fields from the current journal entry
.br
\fBsd_journal_enumerate_available_unique\fR(3)
\(em Read unique data fields from the journal
.br
\fBsd_journal_enumerate_data\fR(3)
\(em Read data fields from the current journal entry
.br
\fBsd_journal_enumerate_fields\fR(3)
\(em Read used field names from the journal
.br
\fBsd_journal_enumerate_unique\fR(3)
\(em Read unique data fields from the journal
.br
\fBsd_journal_flush_matches\fR(3)
\(em Add or remove entry matches
.br
\fBSD_JOURNAL_FOREACH\fR(3)
\(em Advance or set back the read pointer in the journal
.br
\fBSD_JOURNAL_FOREACH_BACKWARDS\fR(3)
\(em Advance or set back the read pointer in the journal
.br
\fBSD_JOURNAL_FOREACH_DATA\fR(3)
\(em Read data fields from the current journal entry
.br
\fBSD_JOURNAL_FOREACH_FIELD\fR(3)
\(em Read used field names from the journal
.br
\fBSD_JOURNAL_FOREACH_UNIQUE\fR(3)
\(em Read unique data fields from the journal
.br
\fBsd_journal_get_catalog\fR(3)
\(em Retrieve message catalog entry
.br
\fBsd_journal_get_catalog_for_message_id\fR(3)
\(em Retrieve message catalog entry
.br
\fBsd_journal_get_cursor\fR(3)
\(em Get cursor string for or test cursor string against the current journal entry
.br
\fBsd_journal_get_cutoff_monotonic_usec\fR(3)
\(em Read cut\-off timestamps from the current journal entry
.br
\fBsd_journal_get_cutoff_realtime_usec\fR(3)
\(em Read cut\-off timestamps from the current journal entry
.br
\fBsd_journal_get_data\fR(3)
\(em Read data fields from the current journal entry
.br
\fBsd_journal_get_data_threshold\fR(3)
\(em Read data fields from the current journal entry
.br
\fBsd_journal_get_events\fR(3)
\(em Journal change notification interface
.br
\fBsd_journal_get_fd\fR(3)
\(em Journal change notification interface
.br
\fBsd_journal_get_monotonic_usec\fR(3)
\(em Read timestamps from the current journal entry
.br
\fBsd_journal_get_realtime_usec\fR(3)
\(em Read timestamps from the current journal entry
.br
\fBsd_journal_get_timeout\fR(3)
\(em Journal change notification interface
.br
\fBsd_journal_get_usage\fR(3)
\(em Journal disk usage
.br
\fBsd_journal_has_persistent_files\fR(3)
\(em Query availability of runtime or persistent journal files
.br
\fBsd_journal_has_runtime_files\fR(3)
\(em Query availability of runtime or persistent journal files
.br
\fBSD_JOURNAL_INCLUDE_DEFAULT_NAMESPACE\fR(3)
\(em Open the system journal for reading
.br
\fBSD_JOURNAL_INVALIDATE\fR(3)
\(em Journal change notification interface
.br
\fBSD_JOURNAL_LOCAL_ONLY\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_next\fR(3)
\(em Advance or set back the read pointer in the journal
.br
\fBsd_journal_next_skip\fR(3)
\(em Advance or set back the read pointer in the journal
.br
\fBSD_JOURNAL_NOP\fR(3)
\(em Journal change notification interface
.br
\fBsd_journal_open\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_open_directory\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_open_directory_fd\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_open_files\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_open_files_fd\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_open_namespace\fR(3)
\(em Open the system journal for reading
.br
\fBSD_JOURNAL_OS_ROOT\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_perror\fR(3)
\(em Submit log entries to the journal
.br
\fBsd_journal_perror_with_location\fR(3)
\(em Submit log entries to the journal
.br
\fBsd_journal_previous\fR(3)
\(em Advance or set back the read pointer in the journal
.br
\fBsd_journal_previous_skip\fR(3)
\(em Advance or set back the read pointer in the journal
.br
\fBsd_journal_print\fR(3)
\(em Submit log entries to the journal
.br
\fBsd_journal_print_with_location\fR(3)
\(em Submit log entries to the journal
.br
\fBsd_journal_printv\fR(3)
\(em Submit log entries to the journal
.br
\fBsd_journal_printv_with_location\fR(3)
\(em Submit log entries to the journal
.br
\fBsd_journal_process\fR(3)
\(em Journal change notification interface
.br
\fBsd_journal_query_unique\fR(3)
\(em Read unique data fields from the journal
.br
\fBsd_journal_reliable_fd\fR(3)
\(em Journal change notification interface
.br
\fBsd_journal_restart_data\fR(3)
\(em Read data fields from the current journal entry
.br
\fBsd_journal_restart_fields\fR(3)
\(em Read used field names from the journal
.br
\fBsd_journal_restart_unique\fR(3)
\(em Read unique data fields from the journal
.br
\fBSD_JOURNAL_RUNTIME_ONLY\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_seek_cursor\fR(3)
\(em Seek to a position in the journal
.br
\fBsd_journal_seek_head\fR(3)
\(em Seek to a position in the journal
.br
\fBsd_journal_seek_monotonic_usec\fR(3)
\(em Seek to a position in the journal
.br
\fBsd_journal_seek_realtime_usec\fR(3)
\(em Seek to a position in the journal
.br
\fBsd_journal_seek_tail\fR(3)
\(em Seek to a position in the journal
.br
\fBsd_journal_send\fR(3)
\(em Submit log entries to the journal
.br
\fBsd_journal_send_with_location\fR(3)
\(em Submit log entries to the journal
.br
\fBsd_journal_sendv\fR(3)
\(em Submit log entries to the journal
.br
\fBsd_journal_sendv_with_location\fR(3)
\(em Submit log entries to the journal
.br
\fBsd_journal_set_data_threshold\fR(3)
\(em Read data fields from the current journal entry
.br
\fBsd_journal_stream_fd\fR(3)
\(em Create log stream file descriptor to the journal
.br
\fBSD_JOURNAL_SUPPRESS_LOCATION\fR(3)
\(em Submit log entries to the journal
.br
\fBSD_JOURNAL_SYSTEM\fR(3)
\(em Open the system journal for reading
.br
\fBsd_journal_test_cursor\fR(3)
\(em Get cursor string for or test cursor string against the current journal entry
.br
\fBsd_journal_wait\fR(3)
\(em Journal change notification interface
.br
\fBsd_listen_fds\fR(3)
\(em Check for file descriptors passed by the system manager
.br
\fBSD_LISTEN_FDS_START\fR(3)
\(em Check for file descriptors passed by the system manager
.br
\fBsd_listen_fds_with_names\fR(3)
\(em Check for file descriptors passed by the system manager
.br
\fBsd_login_monitor\fR(3)
\(em Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_flush\fR(3)
\(em Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_get_events\fR(3)
\(em Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_get_fd\fR(3)
\(em Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_get_timeout\fR(3)
\(em Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_new\fR(3)
\(em Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_unref\fR(3)
\(em Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_unrefp\fR(3)
\(em Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_machine_get_class\fR(3)
\(em Determine the class and network interface indices of a locally running virtual machine or container
.br
\fBsd_machine_get_ifindices\fR(3)
\(em Determine the class and network interface indices of a locally running virtual machine or container
.br
\fBSD_NOTICE\fR(3)
\(em APIs for new\-style daemons
.br
\fBsd_notify\fR(3)
\(em Notify service manager about start\-up completion and other service status changes
.br
\fBsd_notify_barrier\fR(3)
\(em Notify service manager about start\-up completion and other service status changes
.br
\fBsd_notifyf\fR(3)
\(em Notify service manager about start\-up completion and other service status changes
.br
\fBsd_path_lookup\fR(3)
\(em Query well\-known file system paths
.br
\fBsd_path_lookup_strv\fR(3)
\(em Query well\-known file system paths
.br
\fBsd_peer_get_cgroup\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_peer_get_machine_name\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_peer_get_owner_uid\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_peer_get_session\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_peer_get_slice\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_peer_get_unit\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_peer_get_user_slice\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_peer_get_user_unit\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_pid_get_cgroup\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_pid_get_machine_name\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_pid_get_owner_uid\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_pid_get_session\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_pid_get_slice\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_pid_get_unit\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_pid_get_user_slice\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_pid_get_user_unit\fR(3)
\(em Determine the owner uid of the user unit or session, or the session, user unit, system unit, container/VM or slice that a specific PID or socket peer belongs to
.br
\fBsd_pid_notify\fR(3)
\(em Notify service manager about start\-up completion and other service status changes
.br
\fBsd_pid_notify_with_fds\fR(3)
\(em Notify service manager about start\-up completion and other service status changes
.br
\fBsd_pid_notifyf\fR(3)
\(em Notify service manager about start\-up completion and other service status changes
.br
\fBsd_seat_can_graphical\fR(3)
\(em Determine state of a specific seat
.br
\fBsd_seat_can_tty\fR(3)
\(em Determine state of a specific seat
.br
\fBsd_seat_get_active\fR(3)
\(em Determine state of a specific seat
.br
\fBsd_seat_get_sessions\fR(3)
\(em Determine state of a specific seat
.br
\fBsd_session_get_class\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_desktop\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_display\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_remote_host\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_remote_user\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_seat\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_service\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_state\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_tty\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_type\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_uid\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_get_vt\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_is_active\fR(3)
\(em Determine state of a specific session
.br
\fBsd_session_is_remote\fR(3)
\(em Determine state of a specific session
.br
\fBsd_uid_get_display\fR(3)
\(em Determine login state of a specific Unix user ID
.br
\fBsd_uid_get_seats\fR(3)
\(em Determine login state of a specific Unix user ID
.br
\fBsd_uid_get_sessions\fR(3)
\(em Determine login state of a specific Unix user ID
.br
\fBsd_uid_get_state\fR(3)
\(em Determine login state of a specific Unix user ID
.br
\fBsd_uid_is_on_seat\fR(3)
\(em Determine login state of a specific Unix user ID
.br
\fBSD_WARNING\fR(3)
\(em APIs for new\-style daemons
.br
\fBsd_watchdog_enabled\fR(3)
\(em Check whether the service manager expects watchdog keep\-alive notifications from a service
.br
\fBshutdown\fR(8)
\(em Halt, power\-off or reboot the machine
.br
\fBsleep.conf.d\fR(5)
\(em Suspend and hibernation configuration file
.br
\fBsysctl.d\fR(5)
\(em Configure kernel parameters at boot
.br
\fBsystem.conf.d\fR(5)
\(em System and session service manager configuration files
.br
\fBsystemctl\fR(1)
\(em Control the systemd system and service manager
.br
\fBsystemd\fR(1)
\(em systemd system and service manager
.br
\fBsystemd-analyze\fR(1)
\(em Analyze and debug system manager
.br
\fBsystemd-ask-password\fR(1)
\(em Query the user for a system password
.br
\fBsystemd-ask-password-console.path\fR(8)
\(em Query the user for system passwords on the console and via wall
.br
\fBsystemd-ask-password-console.service\fR(8)
\(em Query the user for system passwords on the console and via wall
.br
\fBsystemd-ask-password-wall.path\fR(8)
\(em Query the user for system passwords on the console and via wall
.br
\fBsystemd-ask-password-wall.service\fR(8)
\(em Query the user for system passwords on the console and via wall
.br
\fBsystemd-backlight\fR(8)
\(em Load and save the display backlight brightness at boot and shutdown
.br
\fBsystemd-backlight@.service\fR(8)
\(em Load and save the display backlight brightness at boot and shutdown
.br
\fBsystemd-binfmt\fR(8)
\(em Configure additional binary formats for executables at boot
.br
\fBsystemd-binfmt.service\fR(8)
\(em Configure additional binary formats for executables at boot
.br
\fBsystemd-bless-boot\fR(8)
\(em Mark current boot process as successful
.br
\fBsystemd-bless-boot-generator\fR(8)
\(em Pull
.br
\fBsystemd-bless-boot.service\fR(8)
\(em Mark current boot process as successful
.br
\fBsystemd-boot\fR(7)
\(em A simple UEFI boot manager
.br
\fBsystemd-boot-check-no-failures\fR(8)
\(em verify that the system booted up cleanly
.br
\fBsystemd-boot-check-no-failures.service\fR(8)
\(em verify that the system booted up cleanly
.br
\fBsystemd-boot-system-token.service\fR(8)
\(em Generate an initial boot loader system token and random seed
.br
\fBsystemd-cat\fR(1)
\(em Connect a pipeline or program\*(Aqs output with the journal
.br
\fBsystemd-cgls\fR(1)
\(em Recursively show control group contents
.br
\fBsystemd-cgtop\fR(1)
\(em Show top control groups by their resource usage
.br
\fBsystemd-coredump\fR(8)
\(em Acquire, save and process core dumps
.br
\fBsystemd-coredump.socket\fR(8)
\(em Acquire, save and process core dumps
.br
\fBsystemd-coredump@.service\fR(8)
\(em Acquire, save and process core dumps
.br
\fBsystemd-cryptsetup\fR(8)
\(em Full disk decryption logic
.br
\fBsystemd-cryptsetup-generator\fR(8)
\(em Unit generator for
.br
\fBsystemd-cryptsetup@.service\fR(8)
\(em Full disk decryption logic
.br
\fBsystemd-debug-generator\fR(8)
\(em Generator for enabling a runtime debug shell and masking specific units at boot
.br
\fBsystemd-delta\fR(1)
\(em Find overridden configuration files
.br
\fBsystemd-detect-virt\fR(1)
\(em Detect execution in a virtualized environment
.br
\fBsystemd-environment-d-generator\fR(8)
\(em Load variables specified by
.br
\fBsystemd-escape\fR(1)
\(em Escape strings for usage in systemd unit names
.br
\fBsystemd-fsck\fR(8)
\(em File system checker logic
.br
\fBsystemd-fsck-root.service\fR(8)
\(em File system checker logic
.br
\fBsystemd-fsck@.service\fR(8)
\(em File system checker logic
.br
\fBsystemd-fstab-generator\fR(8)
\(em Unit generator for /etc/fstab
.br
\fBsystemd-getty-generator\fR(8)
\(em Generator for enabling getty instances on the console
.br
\fBsystemd-gpt-auto-generator\fR(8)
\(em Generator for automatically discovering and mounting root,
.br
\fBsystemd-growfs\fR(8)
\(em Creating and growing file systems on demand
.br
\fBsystemd-growfs@.service\fR(8)
\(em Creating and growing file systems on demand
.br
\fBsystemd-halt.service\fR(8)
\(em System shutdown logic
.br
\fBsystemd-hibernate-resume\fR(8)
\(em Resume from hibernation
.br
\fBsystemd-hibernate-resume-generator\fR(8)
\(em Unit generator for resume= kernel parameter
.br
\fBsystemd-hibernate-resume@.service\fR(8)
\(em Resume from hibernation
.br
\fBsystemd-hibernate.service\fR(8)
\(em System sleep state logic
.br
\fBsystemd-hostnamed\fR(8)
\(em Daemon to control system hostname from programs
.br
\fBsystemd-hostnamed.service\fR(8)
\(em Daemon to control system hostname from programs
.br
\fBsystemd-hwdb\fR(8)
\(em hardware database management tool
.br
\fBsystemd-hybrid-sleep.service\fR(8)
\(em System sleep state logic
.br
\fBsystemd-id128\fR(1)
\(em Generate and print sd\-128 identifiers
.br
\fBsystemd-importd\fR(8)
\(em VM and container image import and export service
.br
\fBsystemd-importd.service\fR(8)
\(em VM and container image import and export service
.br
\fBsystemd-inhibit\fR(1)
\(em Execute a program with an inhibition lock taken
.br
\fBsystemd-initctl\fR(8)
\(em /dev/initctl compatibility
.br
\fBsystemd-initctl.service\fR(8)
\(em /dev/initctl compatibility
.br
\fBsystemd-initctl.socket\fR(8)
\(em /dev/initctl compatibility
.br
\fBsystemd-journald\fR(8)
\(em Journal service
.br
\fBsystemd-journald-audit.socket\fR(8)
\(em Journal service
.br
\fBsystemd-journald-dev-log.socket\fR(8)
\(em Journal service
.br
\fBsystemd-journald-varlink@.socket\fR(8)
\(em Journal service
.br
\fBsystemd-journald.service\fR(8)
\(em Journal service
.br
\fBsystemd-journald.socket\fR(8)
\(em Journal service
.br
\fBsystemd-journald@.service\fR(8)
\(em Journal service
.br
\fBsystemd-journald@.socket\fR(8)
\(em Journal service
.br
\fBsystemd-kexec.service\fR(8)
\(em System shutdown logic
.br
\fBsystemd-localed\fR(8)
\(em Locale bus mechanism
.br
\fBsystemd-localed.service\fR(8)
\(em Locale bus mechanism
.br
\fBsystemd-logind\fR(8)
\(em Login manager
.br
\fBsystemd-logind.service\fR(8)
\(em Login manager
.br
\fBsystemd-machine-id-commit.service\fR(8)
\(em Commit a transient machine ID to disk
.br
\fBsystemd-machine-id-setup\fR(1)
\(em Initialize the machine ID in /etc/machine\-id
.br
\fBsystemd-machined\fR(8)
\(em Virtual machine and container registration manager
.br
\fBsystemd-machined.service\fR(8)
\(em Virtual machine and container registration manager
.br
\fBsystemd-makefs\fR(8)
\(em Creating and growing file systems on demand
.br
\fBsystemd-makefs@.service\fR(8)
\(em Creating and growing file systems on demand
.br
\fBsystemd-mkswap@.service\fR(8)
\(em Creating and growing file systems on demand
.br
\fBsystemd-modules-load\fR(8)
\(em Load kernel modules at boot
.br
\fBsystemd-modules-load.service\fR(8)
\(em Load kernel modules at boot
.br
\fBsystemd-mount\fR(1)
\(em Establish and destroy transient mount or auto\-mount points
.br
\fBsystemd-network-generator\fR(8)
\(em Generate network configuration from the kernel command line
.br
\fBsystemd-network-generator.service\fR(8)
\(em Generate network configuration from the kernel command line
.br
\fBsystemd-networkd\fR(8)
\(em Network manager
.br
\fBsystemd-networkd-wait-online\fR(8)
\(em Wait for network to come online
.br
\fBsystemd-networkd-wait-online.service\fR(8)
\(em Wait for network to come online
.br
\fBsystemd-networkd.service\fR(8)
\(em Network manager
.br
\fBsystemd-notify\fR(1)
\(em Notify service manager about start\-up completion and other daemon status changes
.br
\fBsystemd-nspawn\fR(1)
\(em Spawn a command or OS in a light\-weight container
.br
\fBsystemd-path\fR(1)
\(em List and query system and user paths
.br
\fBsystemd-portabled\fR(8)
\(em Portable service manager
.br
\fBsystemd-portabled.service\fR(8)
\(em Portable service manager
.br
\fBsystemd-poweroff.service\fR(8)
\(em System shutdown logic
.br
\fBsystemd-pstore\fR(8)
\(em A service to archive contents of pstore
.br
\fBsystemd-pstore.service\fR(8)
\(em A service to archive contents of pstore
.br
\fBsystemd-quotacheck\fR(8)
\(em File system quota checker logic
.br
\fBsystemd-quotacheck.service\fR(8)
\(em File system quota checker logic
.br
\fBsystemd-random-seed\fR(8)
\(em Load and save the system random seed at boot and shutdown
.br
\fBsystemd-random-seed.service\fR(8)
\(em Load and save the system random seed at boot and shutdown
.br
\fBsystemd-rc-local-generator\fR(8)
\(em Compatibility generator for starting
.br
\fBsystemd-reboot.service\fR(8)
\(em System shutdown logic
.br
\fBsystemd-remount-fs\fR(8)
\(em Remount root and kernel file systems
.br
\fBsystemd-remount-fs.service\fR(8)
\(em Remount root and kernel file systems
.br
\fBsystemd-repart\fR(8)
\(em Automatically grow and add partitions
.br
\fBsystemd-repart.service\fR(8)
\(em Automatically grow and add partitions
.br
\fBsystemd-resolved\fR(8)
\(em Network Name Resolution manager
.br
\fBsystemd-resolved.service\fR(8)
\(em Network Name Resolution manager
.br
\fBsystemd-rfkill\fR(8)
\(em Load and save the RF kill switch state at boot and change
.br
\fBsystemd-rfkill.service\fR(8)
\(em Load and save the RF kill switch state at boot and change
.br
\fBsystemd-rfkill.socket\fR(8)
\(em Load and save the RF kill switch state at boot and change
.br
\fBsystemd-run\fR(1)
\(em Run programs in transient scope units, service units, or path\-, socket\-, or timer\-triggered service units
.br
\fBsystemd-run-generator\fR(8)
\(em Generator for invoking commands specified on the kernel command line as system service
.br
\fBsystemd-shutdown\fR(8)
\(em System shutdown logic
.br
\fBsystemd-sleep\fR(8)
\(em System sleep state logic
.br
\fBsystemd-sleep.conf\fR(5)
\(em Suspend and hibernation configuration file
.br
\fBsystemd-socket-activate\fR(1)
\(em Test socket activation of daemons
.br
\fBsystemd-socket-proxyd\fR(8)
\(em Bidirectionally proxy local sockets to another (possibly remote) socket
.br
\fBsystemd-suspend-then-hibernate.service\fR(8)
\(em System sleep state logic
.br
\fBsystemd-suspend.service\fR(8)
\(em System sleep state logic
.br
\fBsystemd-sysctl\fR(8)
\(em Configure kernel parameters at boot
.br
\fBsystemd-sysctl.service\fR(8)
\(em Configure kernel parameters at boot
.br
\fBsystemd-system-update-generator\fR(8)
\(em Generator for redirecting boot to offline update mode
.br
\fBsystemd-system.conf\fR(5)
\(em System and session service manager configuration files
.br
\fBsystemd-sysusers\fR(8)
\(em Allocate system users and groups
.br
\fBsystemd-sysusers.service\fR(8)
\(em Allocate system users and groups
.br
\fBsystemd-sysv-generator\fR(8)
\(em Unit generator for SysV init scripts
.br
\fBsystemd-time-wait-sync\fR(8)
\(em Wait until kernel time is synchronized
.br
\fBsystemd-time-wait-sync.service\fR(8)
\(em Wait until kernel time is synchronized
.br
\fBsystemd-timedated\fR(8)
\(em Time and date bus mechanism
.br
\fBsystemd-timedated.service\fR(8)
\(em Time and date bus mechanism
.br
\fBsystemd-timesyncd\fR(8)
\(em Network Time Synchronization
.br
\fBsystemd-timesyncd.service\fR(8)
\(em Network Time Synchronization
.br
\fBsystemd-tmpfiles\fR(8)
\(em Creates, deletes and cleans up volatile and temporary files and directories
.br
\fBsystemd-tmpfiles-clean.service\fR(8)
\(em Creates, deletes and cleans up volatile and temporary files and directories
.br
\fBsystemd-tmpfiles-clean.timer\fR(8)
\(em Creates, deletes and cleans up volatile and temporary files and directories
.br
\fBsystemd-tmpfiles-setup-dev.service\fR(8)
\(em Creates, deletes and cleans up volatile and temporary files and directories
.br
\fBsystemd-tmpfiles-setup.service\fR(8)
\(em Creates, deletes and cleans up volatile and temporary files and directories
.br
\fBsystemd-tty-ask-password-agent\fR(1)
\(em List or process pending systemd password requests
.br
\fBsystemd-udev-settle.service\fR(8)
\(em Wait for all pending udev events to be handled
.br
\fBsystemd-udevd\fR(8)
\(em Device event managing daemon
.br
\fBsystemd-udevd-control.socket\fR(8)
\(em Device event managing daemon
.br
\fBsystemd-udevd-kernel.socket\fR(8)
\(em Device event managing daemon
.br
\fBsystemd-udevd.service\fR(8)
\(em Device event managing daemon
.br
\fBsystemd-umount\fR(1)
\(em Establish and destroy transient mount or auto\-mount points
.br
\fBsystemd-update-done\fR(8)
\(em Mark
.br
\fBsystemd-update-done.service\fR(8)
\(em Mark
.br
\fBsystemd-update-utmp\fR(8)
\(em Write audit and utmp updates at bootup, runlevel changes and shutdown
.br
\fBsystemd-update-utmp-runlevel.service\fR(8)
\(em Write audit and utmp updates at bootup, runlevel changes and shutdown
.br
\fBsystemd-update-utmp.service\fR(8)
\(em Write audit and utmp updates at bootup, runlevel changes and shutdown
.br
\fBsystemd-user-runtime-dir\fR(5)
\(em System units to start the user manager
.br
\fBsystemd-user-sessions\fR(8)
\(em Permit user logins after boot, prohibit user logins at shutdown
.br
\fBsystemd-user-sessions.service\fR(8)
\(em Permit user logins after boot, prohibit user logins at shutdown
.br
\fBsystemd-user.conf\fR(5)
\(em System and session service manager configuration files
.br
\fBsystemd-vconsole-setup\fR(8)
\(em Configure the virtual consoles
.br
\fBsystemd-vconsole-setup.service\fR(8)
\(em Configure the virtual consoles
.br
\fBsystemd-veritysetup\fR(8)
\(em Disk integrity protection logic
.br
\fBsystemd-veritysetup-generator\fR(8)
\(em Unit generator for integrity protected block devices
.br
\fBsystemd-veritysetup@.service\fR(8)
\(em Disk integrity protection logic
.br
\fBsystemd-volatile-root\fR(8)
\(em Make the root file system volatile
.br
\fBsystemd-volatile-root.service\fR(8)
\(em Make the root file system volatile
.br
\fBsystemd-xdg-autostart-generator\fR(8)
\(em User unit generator for XDG autostart files
.br
\fBsystemd.automount\fR(5)
\(em Automount unit configuration
.br
\fBsystemd.device\fR(5)
\(em Device unit configuration
.br
\fBsystemd.directives\fR(7)
\(em Index of configuration directives
.br
\fBsystemd.dnssd\fR(5)
\(em DNS\-SD configuration
.br
\fBsystemd.environment-generator\fR(7)
\(em systemd environment file generators
.br
\fBsystemd.exec\fR(5)
\(em Execution environment configuration
.br
\fBsystemd.generator\fR(7)
\(em systemd unit generators
.br
\fBsystemd.journal-fields\fR(7)
\(em Special journal fields
.br
\fBsystemd.kill\fR(5)
\(em Process killing procedure configuration
.br
\fBsystemd.link\fR(5)
\(em Network device configuration
.br
\fBsystemd.mount\fR(5)
\(em Mount unit configuration
.br
\fBsystemd.negative\fR(5)
\(em DNSSEC trust anchor configuration files
.br
\fBsystemd.net-naming-scheme\fR(7)
\(em Network device naming schemes
.br
\fBsystemd.netdev\fR(5)
\(em Virtual Network Device configuration
.br
\fBsystemd.network\fR(5)
\(em Network configuration
.br
\fBsystemd.nspawn\fR(5)
\(em Container settings
.br
\fBsystemd.offline-updates\fR(7)
\(em Implementation of offline updates in systemd
.br
\fBsystemd.path\fR(5)
\(em Path unit configuration
.br
\fBsystemd.positive\fR(5)
\(em DNSSEC trust anchor configuration files
.br
\fBsystemd.preset\fR(5)
\(em Service enablement presets
.br
\fBsystemd.resource-control\fR(5)
\(em Resource control unit settings
.br
\fBsystemd.scope\fR(5)
\(em Scope unit configuration
.br
\fBsystemd.service\fR(5)
\(em Service unit configuration
.br
\fBsystemd.slice\fR(5)
\(em Slice unit configuration
.br
\fBsystemd.socket\fR(5)
\(em Socket unit configuration
.br
\fBsystemd.special\fR(7)
\(em Special systemd units
.br
\fBsystemd.swap\fR(5)
\(em Swap unit configuration
.br
\fBsystemd.syntax\fR(7)
\(em General syntax of systemd configuration files
.br
\fBsystemd.target\fR(5)
\(em Target unit configuration
.br
\fBsystemd.time\fR(7)
\(em Time and date specifications
.br
\fBsystemd.timer\fR(5)
\(em Timer unit configuration
.br
\fBsystemd.unit\fR(5)
\(em Unit configuration
.br

.SH "T"
.PP
\fBtelinit\fR(8)
\(em Change SysV runlevel
.br
\fBtimedatectl\fR(1)
\(em Control the system time and date
.br
\fBtimesyncd.conf\fR(5)
\(em Network Time Synchronization configuration files
.br
\fBtimesyncd.conf.d\fR(5)
\(em Network Time Synchronization configuration files
.br
\fBtmpfiles.d\fR(5)
\(em Configuration for creation, deletion and cleaning of volatile and temporary files
.br

.SH "U"
.PP
\fBudev\fR(7)
\(em Dynamic device management
.br
\fBudev.conf\fR(5)
\(em Configuration for device event managing daemon
.br
\fBudev_device_get_action\fR(3)
\(em Query device properties
.br
\fBudev_device_get_devlinks_list_entry\fR(3)
\(em Retrieve or set device attributes
.br
\fBudev_device_get_devnode\fR(3)
\(em Query device properties
.br
\fBudev_device_get_devnum\fR(3)
\(em Query device properties
.br
\fBudev_device_get_devpath\fR(3)
\(em Query device properties
.br
\fBudev_device_get_devtype\fR(3)
\(em Query device properties
.br
\fBudev_device_get_driver\fR(3)
\(em Query device properties
.br
\fBudev_device_get_is_initialized\fR(3)
\(em Query device properties
.br
\fBudev_device_get_parent\fR(3)
\(em Query device properties
.br
\fBudev_device_get_parent_with_subsystem_devtype\fR(3)
\(em Query device properties
.br
\fBudev_device_get_properties_list_entry\fR(3)
\(em Retrieve or set device attributes
.br
\fBudev_device_get_property_value\fR(3)
\(em Retrieve or set device attributes
.br
\fBudev_device_get_subsystem\fR(3)
\(em Query device properties
.br
\fBudev_device_get_sysattr_list_entry\fR(3)
\(em Retrieve or set device attributes
.br
\fBudev_device_get_sysattr_value\fR(3)
\(em Retrieve or set device attributes
.br
\fBudev_device_get_sysname\fR(3)
\(em Query device properties
.br
\fBudev_device_get_sysnum\fR(3)
\(em Query device properties
.br
\fBudev_device_get_syspath\fR(3)
\(em Query device properties
.br
\fBudev_device_get_tags_list_entry\fR(3)
\(em Retrieve or set device attributes
.br
\fBudev_device_get_udev\fR(3)
\(em Query device properties
.br
\fBudev_device_has_tag\fR(3)
\(em Retrieve or set device attributes
.br
\fBudev_device_new_from_device_id\fR(3)
\(em Create, acquire and release a udev device object
.br
\fBudev_device_new_from_devnum\fR(3)
\(em Create, acquire and release a udev device object
.br
\fBudev_device_new_from_environment\fR(3)
\(em Create, acquire and release a udev device object
.br
\fBudev_device_new_from_subsystem_sysname\fR(3)
\(em Create, acquire and release a udev device object
.br
\fBudev_device_new_from_syspath\fR(3)
\(em Create, acquire and release a udev device object
.br
\fBudev_device_ref\fR(3)
\(em Create, acquire and release a udev device object
.br
\fBudev_device_set_sysattr_value\fR(3)
\(em Retrieve or set device attributes
.br
\fBudev_device_unref\fR(3)
\(em Create, acquire and release a udev device object
.br
\fBudev_enumerate_add_match_is_initialized\fR(3)
\(em Modify filters
.br
\fBudev_enumerate_add_match_parent\fR(3)
\(em Modify filters
.br
\fBudev_enumerate_add_match_property\fR(3)
\(em Modify filters
.br
\fBudev_enumerate_add_match_subsystem\fR(3)
\(em Modify filters
.br
\fBudev_enumerate_add_match_sysattr\fR(3)
\(em Modify filters
.br
\fBudev_enumerate_add_match_sysname\fR(3)
\(em Modify filters
.br
\fBudev_enumerate_add_match_tag\fR(3)
\(em Modify filters
.br
\fBudev_enumerate_add_nomatch_subsystem\fR(3)
\(em Modify filters
.br
\fBudev_enumerate_add_nomatch_sysattr\fR(3)
\(em Modify filters
.br
\fBudev_enumerate_add_syspath\fR(3)
\(em Query or modify a udev enumerate object
.br
\fBudev_enumerate_get_list_entry\fR(3)
\(em Query or modify a udev enumerate object
.br
\fBudev_enumerate_get_udev\fR(3)
\(em Query or modify a udev enumerate object
.br
\fBudev_enumerate_new\fR(3)
\(em Create, acquire and release a udev enumerate object
.br
\fBudev_enumerate_ref\fR(3)
\(em Create, acquire and release a udev enumerate object
.br
\fBudev_enumerate_scan_devices\fR(3)
\(em Query or modify a udev enumerate object
.br
\fBudev_enumerate_scan_subsystems\fR(3)
\(em Query or modify a udev enumerate object
.br
\fBudev_enumerate_unref\fR(3)
\(em Create, acquire and release a udev enumerate object
.br
\fBudev_list_entry\fR(3)
\(em Iterate and access udev lists
.br
\fBudev_list_entry_get_by_name\fR(3)
\(em Iterate and access udev lists
.br
\fBudev_list_entry_get_name\fR(3)
\(em Iterate and access udev lists
.br
\fBudev_list_entry_get_next\fR(3)
\(em Iterate and access udev lists
.br
\fBudev_list_entry_get_value\fR(3)
\(em Iterate and access udev lists
.br
\fBudev_monitor_enable_receiving\fR(3)
\(em Query and modify device monitor
.br
\fBudev_monitor_filter_add_match_subsystem_devtype\fR(3)
\(em Modify filters
.br
\fBudev_monitor_filter_add_match_tag\fR(3)
\(em Modify filters
.br
\fBudev_monitor_filter_remove\fR(3)
\(em Modify filters
.br
\fBudev_monitor_filter_update\fR(3)
\(em Modify filters
.br
\fBudev_monitor_get_fd\fR(3)
\(em Query and modify device monitor
.br
\fBudev_monitor_get_udev\fR(3)
\(em Query and modify device monitor
.br
\fBudev_monitor_new_from_netlink\fR(3)
\(em Create, acquire and release a udev monitor object
.br
\fBudev_monitor_receive_device\fR(3)
\(em Query and modify device monitor
.br
\fBudev_monitor_ref\fR(3)
\(em Create, acquire and release a udev monitor object
.br
\fBudev_monitor_set_receive_buffer_size\fR(3)
\(em Query and modify device monitor
.br
\fBudev_monitor_unref\fR(3)
\(em Create, acquire and release a udev monitor object
.br
\fBudev_new\fR(3)
\(em Create, acquire and release a udev context object
.br
\fBudev_ref\fR(3)
\(em Create, acquire and release a udev context object
.br
\fBudev_unref\fR(3)
\(em Create, acquire and release a udev context object
.br
\fBudevadm\fR(8)
\(em udev management tool
.br
\fBuser-runtime-dir@.service\fR(5)
\(em System units to start the user manager
.br
\fBuser.conf.d\fR(5)
\(em System and session service manager configuration files
.br
\fBuser@.service\fR(5)
\(em System units to start the user manager
.br

.SH "V"
.PP
\fBvconsole.conf\fR(5)
\(em Configuration file for the virtual console
.br

.SH "SEE ALSO"
.PP
\fBsystemd.directives\fR(7)
.PP
This index contains 976 entries, referring to 337 individual manual pages\&.
