'\" t
.TH "SYSTEMD\-VERITYSETUP\-GENERATOR" "8" "" "systemd 246" "systemd-veritysetup-generator"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-veritysetup-generator \- Unit generator for integrity protected block devices
.SH "SYNOPSIS"
.PP
/usr/lib/systemd/system\-generators/systemd\-veritysetup\-generator
.SH "DESCRIPTION"
.PP
systemd\-veritysetup\-generator
is a generator that translates kernel command line options configuring integrity\-protected block devices (verity) into native systemd units early at boot and when configuration of the system manager is reloaded\&. This will create
\fBsystemd-veritysetup@.service\fR(8)
units as necessary\&.
.PP
Currently, only a single verity device may be set up with this generator, backing the root file system of the OS\&.
.PP
systemd\-veritysetup\-generator
implements
\fBsystemd.generator\fR(7)\&.
.SH "KERNEL COMMAND LINE"
.PP
systemd\-veritysetup\-generator
understands the following kernel command line parameters:
.PP
\fIsystemd\&.verity=\fR, \fIrd\&.systemd\&.verity=\fR
.RS 4
Takes a boolean argument\&. Defaults to
"yes"\&. If
"no", disables the generator entirely\&.
\fIrd\&.systemd\&.verity=\fR
is honored only by the initial RAM disk (initrd) while
\fIsystemd\&.verity=\fR
is honored by both the host system and the initrd\&.
.RE
.PP
\fIroothash=\fR
.RS 4
Takes a root hash value for the root file system\&. Expects a hash value formatted in hexadecimal characters of the appropriate length (i\&.e\&. most likely 256 bit/64 characters, or longer)\&. If not specified via
\fIsystemd\&.verity_root_data=\fR
and
\fIsystemd\&.verity_root_hash=\fR, the hash and data devices to use are automatically derived from the specified hash value\&. Specifically, the data partition device is looked for under a GPT partition UUID derived from the first 128bit of the root hash, the hash partition device is looked for under a GPT partition UUID derived from the last 128bit of the root hash\&. Hence it is usually sufficient to specify the root hash to boot from an integrity protected root file system, as device paths are automatically determined from it \(em as long as the partition table is properly set up\&.
.RE
.PP
\fIsystemd\&.verity_root_data=\fR, \fIsystemd\&.verity_root_hash=\fR
.RS 4
These two settings take block device paths as arguments and may be used to explicitly configure the data partition and hash partition to use for setting up the integrity protection for the root file system\&. If not specified, these paths are automatically derived from the
\fIroothash=\fR
argument (see above)\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd-veritysetup@.service\fR(8),
\fBveritysetup\fR(8),
\fBsystemd-fstab-generator\fR(8)
